Repository OpenBMB/UltraRAG, pull requests merged in 2025-09, with the labels that each got.

#83 Add: conda deps
  environment.yml
Labels: documentation

#104 fix: prompt template for deepresearch-like pipeline
  prompt/webnote_fill_page.jinja
  prompt/webnote_gen_subq.jinja
  prompt/webnote_init_page.jinja
Labels: bug

#106 Support custom parameter file paths via CLI argument
  src/ultrarag/client.py
Labels: enhancement

#107 fix: acc calc error when pred is none
  servers/evaluation/src/evaluation.py
Labels: bug
